### ISSUE TITLE
Add Household Size Explanation to the First Question

### ISSUE THREAD

**Issue by genevievenielsen** [mRelief/documents_api#132]
Add this copy - 

"This refers to the number of people who purchase and prepare food with you."

**Comment by alexsoble** [comment]
Question: Would this be next to the "My Family" option?

Like this:

```
How many people are you applying for?

( ) Just Me.
( ) My Family. (This refers to the number of people who purchase and prepare food with you.)
```

**Comment by alexsoble** [comment]
Or:

```
How many people are you applying for? (This refers to the number of people who purchase and prepare food with you.)

( ) Just Me.
( ) My Family. 
```

**Comment by alexsoble** [comment]
OK, I think the second option sounds a little bit better.

**Comment by alexsoble** [comment]
Note from Vieve & Rose call about how best to do this: 

+ Use hover mechanism to show explanations. 
+ "I buy and cook food by myself."
+ "I buy and cook food with my family."
