### ISSUE TITLE
Add Note to Select All Questions

### ISSUE THREAD

**Issue by genevievenielsen** [mRelief/documents_api#141]
You can select multiple options

**Comment by alexsoble** [comment]
@genevievenielsen @RoseAfriyie Preferences?
![screen shot 2016-08-18 at 1 26 35 pm](https://cloud.githubusercontent.com/assets/3209501/17785695/73d82f9a-6547-11e6-828a-01524b76e9aa.png)
![screen shot 2016-08-18 at 1 25 25 pm](https://cloud.githubusercontent.com/assets/3209501/17785696/73ef6ae8-6547-11e6-9ff3-1656f5165135.png)

**Comment by genevievenielsen** [comment]
@alexsoble @RoseAfriyie I prefer the Note above because I worry that people might initially miss the Note below, but I don't have a strong preference either way. Thanks Alex for working on this!

**Comment by alexsoble** [comment]
@genevievenielsen 👍
