### ISSUE TITLE
Make sure that 2 initial text messages are sent in the correct order

### ISSUE THREAD

**Issue by genevievenielsen** [mRelief/documents_api#240]
Sometimes the initial welcome messages are sent by Twilio in the wrong order
![img_1738](https://cloud.githubusercontent.com/assets/8093485/18454288/16010c5e-7909-11e6-8ce9-648166c5a98a.PNG)

One potential fix is to check the Twilio status of the first message and only send the second message when the status is either 'delivered' or 'sent'

**Comment by alexsoble** [comment]
Here's a cheap way to do this! https://support.twilio.com/hc/en-us/articles/223134247-Can-my-SMS-messages-arrive-in-order-

(@geneievenielsen and I agree this is a good idea.)
