### ISSUE TITLE
Support multi-member households

### ISSUE THREAD

**Issue by alexsoble** [mRelief/documents_api#25]

**Comment by alexsoble** [comment]
Question phrasing idea from what we learned at Fulton -- AVOID the word "household", people don't connect with it.

How many people are you applying for?
- Just Me
- My Family

... and then if a user clicks "My Family" show more input options for family size.

**Comment by genevievenielsen** [comment]
Closing for this week

**Comment by alexsoble** [comment]
Re-opening for this week!

😊

**Comment by alexsoble** [comment]
Closed via #84, #85, #86.
