### ISSUE TITLE
Add Housing Question and Logic for Residency Questions

### ISSUE THREAD

**Issue by genevievenielsen** [mRelief/documents_api#36]
Provide better residency options based on housing situation

Describe your living situation:
- Renting
- Own home
- Living with family/friends
- Shelter
- None of the above

Only show 'Rent Receipt' if renting
Only show 'Home Owners Insurance' and 'Property Tax Bill' if own home
Only show 'Homeless Shelter Statement' if in shelter

If 'None of the above', show all residency docs

**Comment by alexsoble** [comment]
@genevievenielsen Question, what residency docs should we display if the user clicks "Living with family/friends"?

**Comment by genevievenielsen** [comment]
@alexsoble Oh good point - 

Official name - Letter from Family or Friend
Description - A signed letter from the family or friends that you are living with stating that they are staying there and the length of time they have been there

**Comment by alexsoble** [comment]
Fixed by #62.
