### ISSUE TITLE
Proving Residency for Living Situation Guidance from Martha

### ISSUE THREAD

**Issue by RoseAfriyie** [mRelief/documents_api#54]
Martha has referenced[ this policy](http://www.dhs.state.il.us/page.aspx?Item=13236) to confirm Dwight's method of proving residency was:

If one doesn't have a home, they can provide a statement from a shelter, clinic, or relative with a signature stating that they are staying there and the length of time they have been there.

**Comment by alexsoble** [comment]
Fixed by #62.
